### ISSUE TITLE
JSON file?

### ISSUE THREAD

**Issue by ekawamoto1** [KilroyWasHere-cs-j/WebScraping#6]
https://github.com/KilroyWasHere-cs-j/WebScraping/blob/e3c91de44bcd1c3dc5969cb9ebd5f043deba2f82/Form1FunctionConfig.txt#L1

Perhaps it would be better to maintain this file in JSON format (so stuff that seems to be related, like First, Second, FirstIndex, and SecondIndex, could belong to some hierarchy). Otherwise, if you keep this as a text file, you might use the .INI format (section names in brackets, followed by key-value pairs delimited by =, or something like KEY=value1:value2:... or KEY="value with spaces")

**Comment by KilroyWasHere-cs-j** [comment]
Okay thank you, I'll look into that.

**Comment by KilroyWasHere-cs-j** [comment]
Also I forgot to mention this that's actually a text file not a JSON file.
They're actually booked into it that seems to be how Microsoft does their
configuration files.

**Comment by KilroyWasHere-cs-j** [comment]
This issue has been closed. I figure I'll use a .INI file format. Thanks again for the suggestion.
